# Generated by Django 5.2.15 on 2026-06-22 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtprotoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pds_url', models.URLField()),
                ('issuer', models.URLField()),
                ('token_endpoint', models.URLField()),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('dpop_private_pem', models.TextField()),
                ('dpop_nonce', models.CharField(blank=True, max_length=512)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atproto_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
